//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.08.29 at 10:30:24 AM PDT 
//


package org.readiness.items.domain;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.readiness.items.jaxb package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.readiness.items.jaxb
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Itemrelease }
     * 
     */
    public Itemrelease createItemrelease() {
        return new Itemrelease();
    }

    /**
     * Create an instance of {@link Itemrelease.Item }
     * 
     */
    public Itemrelease.Item createItemreleaseItem() {
        return new Itemrelease.Item();
    }

    /**
     * Create an instance of {@link Itemrelease.Item.KeywordList }
     * 
     */
    public Itemrelease.Item.KeywordList createItemreleaseItemKeywordList() {
        return new Itemrelease.Item.KeywordList();
    }

    /**
     * Create an instance of {@link Itemrelease.Item.KeywordList.Keyword }
     * 
     */
    public Itemrelease.Item.KeywordList.Keyword createItemreleaseItemKeywordListKeyword() {
        return new Itemrelease.Item.KeywordList.Keyword();
    }

    /**
     * Create an instance of {@link Itemrelease.Item.Content }
     * 
     */
    public Itemrelease.Item.Content createItemreleaseItemContent() {
        return new Itemrelease.Item.Content();
    }

    /**
     * Create an instance of {@link Itemrelease.Item.Content.ApipAccessibility }
     * 
     */
    public Itemrelease.Item.Content.ApipAccessibility createItemreleaseItemContentApipAccessibility() {
        return new Itemrelease.Item.Content.ApipAccessibility();
    }

    /**
     * Create an instance of {@link Itemrelease.Item.Content.ApipAccessibility.AccessibilityInfo }
     * 
     */
    public Itemrelease.Item.Content.ApipAccessibility.AccessibilityInfo createItemreleaseItemContentApipAccessibilityAccessibilityInfo() {
        return new Itemrelease.Item.Content.ApipAccessibility.AccessibilityInfo();
    }

    /**
     * Create an instance of {@link Itemrelease.Item.Content.ApipAccessibility.AccessibilityInfo.AccessElement }
     * 
     */
    public Itemrelease.Item.Content.ApipAccessibility.AccessibilityInfo.AccessElement createItemreleaseItemContentApipAccessibilityAccessibilityInfoAccessElement() {
        return new Itemrelease.Item.Content.ApipAccessibility.AccessibilityInfo.AccessElement();
    }

    /**
     * Create an instance of {@link Itemrelease.Item.Content.ApipAccessibility.AccessibilityInfo.AccessElement.RelatedElementInfo }
     * 
     */
    public Itemrelease.Item.Content.ApipAccessibility.AccessibilityInfo.AccessElement.RelatedElementInfo createItemreleaseItemContentApipAccessibilityAccessibilityInfoAccessElementRelatedElementInfo() {
        return new Itemrelease.Item.Content.ApipAccessibility.AccessibilityInfo.AccessElement.RelatedElementInfo();
    }

    /**
     * Create an instance of {@link Itemrelease.Item.Content.Attachmentlist }
     * 
     */
    public Itemrelease.Item.Content.Attachmentlist createItemreleaseItemContentAttachmentlist() {
        return new Itemrelease.Item.Content.Attachmentlist();
    }

    /**
     * Create an instance of {@link Itemrelease.Item.Content.Rubriclist }
     * 
     */
    public Itemrelease.Item.Content.Rubriclist createItemreleaseItemContentRubriclist() {
        return new Itemrelease.Item.Content.Rubriclist();
    }

    /**
     * Create an instance of {@link Itemrelease.Item.Content.Rubriclist.Samplelist }
     * 
     */
    public Itemrelease.Item.Content.Rubriclist.Samplelist createItemreleaseItemContentRubriclistSamplelist() {
        return new Itemrelease.Item.Content.Rubriclist.Samplelist();
    }

    /**
     * Create an instance of {@link Itemrelease.Item.Resourceslist }
     * 
     */
    public Itemrelease.Item.Resourceslist createItemreleaseItemResourceslist() {
        return new Itemrelease.Item.Resourceslist();
    }

    /**
     * Create an instance of {@link Itemrelease.Item.Attriblist }
     * 
     */
    public Itemrelease.Item.Attriblist createItemreleaseItemAttriblist() {
        return new Itemrelease.Item.Attriblist();
    }

    /**
     * Create an instance of {@link NewDataSet }
     * 
     */
    public NewDataSet createNewDataSet() {
        return new NewDataSet();
    }

    /**
     * Create an instance of {@link Itemrelease.Item.Tutorial }
     * 
     */
    public Itemrelease.Item.Tutorial createItemreleaseItemTutorial() {
        return new Itemrelease.Item.Tutorial();
    }

    /**
     * Create an instance of {@link Itemrelease.Item.MachineRubric }
     * 
     */
    public Itemrelease.Item.MachineRubric createItemreleaseItemMachineRubric() {
        return new Itemrelease.Item.MachineRubric();
    }

    /**
     * Create an instance of {@link Itemrelease.Item.RendererSpec }
     * 
     */
    public Itemrelease.Item.RendererSpec createItemreleaseItemRendererSpec() {
        return new Itemrelease.Item.RendererSpec();
    }

    /**
     * Create an instance of {@link Itemrelease.Item.KeywordList.Keyword.Html }
     * 
     */
    public Itemrelease.Item.KeywordList.Keyword.Html createItemreleaseItemKeywordListKeywordHtml() {
        return new Itemrelease.Item.KeywordList.Keyword.Html();
    }

    /**
     * Create an instance of {@link Itemrelease.Item.Content.ApipAccessibility.AccessibilityInfo.AccessElement.ContentLinkInfo }
     * 
     */
    public Itemrelease.Item.Content.ApipAccessibility.AccessibilityInfo.AccessElement.ContentLinkInfo createItemreleaseItemContentApipAccessibilityAccessibilityInfoAccessElementContentLinkInfo() {
        return new Itemrelease.Item.Content.ApipAccessibility.AccessibilityInfo.AccessElement.ContentLinkInfo();
    }

    /**
     * Create an instance of {@link Itemrelease.Item.Content.ApipAccessibility.AccessibilityInfo.AccessElement.RelatedElementInfo.ReadAloud }
     * 
     */
    public Itemrelease.Item.Content.ApipAccessibility.AccessibilityInfo.AccessElement.RelatedElementInfo.ReadAloud createItemreleaseItemContentApipAccessibilityAccessibilityInfoAccessElementRelatedElementInfoReadAloud() {
        return new Itemrelease.Item.Content.ApipAccessibility.AccessibilityInfo.AccessElement.RelatedElementInfo.ReadAloud();
    }

    /**
     * Create an instance of {@link Itemrelease.Item.Content.ApipAccessibility.AccessibilityInfo.AccessElement.RelatedElementInfo.BrailleText }
     * 
     */
    public Itemrelease.Item.Content.ApipAccessibility.AccessibilityInfo.AccessElement.RelatedElementInfo.BrailleText createItemreleaseItemContentApipAccessibilityAccessibilityInfoAccessElementRelatedElementInfoBrailleText() {
        return new Itemrelease.Item.Content.ApipAccessibility.AccessibilityInfo.AccessElement.RelatedElementInfo.BrailleText();
    }

    /**
     * Create an instance of {@link Itemrelease.Item.Content.Attachmentlist.Attachment }
     * 
     */
    public Itemrelease.Item.Content.Attachmentlist.Attachment createItemreleaseItemContentAttachmentlistAttachment() {
        return new Itemrelease.Item.Content.Attachmentlist.Attachment();
    }

    /**
     * Create an instance of {@link Itemrelease.Item.Content.Rubriclist.Rubric }
     * 
     */
    public Itemrelease.Item.Content.Rubriclist.Rubric createItemreleaseItemContentRubriclistRubric() {
        return new Itemrelease.Item.Content.Rubriclist.Rubric();
    }

    /**
     * Create an instance of {@link Itemrelease.Item.Content.Rubriclist.Samplelist.Sample }
     * 
     */
    public Itemrelease.Item.Content.Rubriclist.Samplelist.Sample createItemreleaseItemContentRubriclistSamplelistSample() {
        return new Itemrelease.Item.Content.Rubriclist.Samplelist.Sample();
    }

    /**
     * Create an instance of {@link Itemrelease.Item.Resourceslist.Resource }
     * 
     */
    public Itemrelease.Item.Resourceslist.Resource createItemreleaseItemResourceslistResource() {
        return new Itemrelease.Item.Resourceslist.Resource();
    }

    /**
     * Create an instance of {@link Itemrelease.Item.Attriblist.Attrib }
     * 
     */
    public Itemrelease.Item.Attriblist.Attrib createItemreleaseItemAttriblistAttrib() {
        return new Itemrelease.Item.Attriblist.Attrib();
    }

}
