//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.09.25 at 01:59:39 PM PDT 
//


package org.cresst.sb.irp.domain.testpackage;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;attribute name="itemid" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="formposition" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="groupposition" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="adminrequired" default="false">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}NMTOKEN">
 *             &lt;enumeration value="true"/>
 *             &lt;enumeration value="false"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *       &lt;attribute name="responserequired" default="false">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}NMTOKEN">
 *             &lt;enumeration value="true"/>
 *             &lt;enumeration value="false"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *       &lt;attribute name="isfieldtest" use="required">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}NMTOKEN">
 *             &lt;enumeration value="true"/>
 *             &lt;enumeration value="false"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *       &lt;attribute name="isactive" use="required">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}NMTOKEN">
 *             &lt;enumeration value="true"/>
 *             &lt;enumeration value="false"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *       &lt;attribute name="blockid" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "")
@XmlRootElement(name = "groupitem")
public class Groupitem {

    @XmlAttribute(name = "itemid", required = true)
    protected String itemid;
    @XmlAttribute(name = "formposition")
    protected String formposition;
    @XmlAttribute(name = "groupposition", required = true)
    protected String groupposition;
    @XmlAttribute(name = "adminrequired")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String adminrequired;
    @XmlAttribute(name = "responserequired")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String responserequired;
    @XmlAttribute(name = "isfieldtest", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String isfieldtest;
    @XmlAttribute(name = "isactive", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String isactive;
    @XmlAttribute(name = "blockid")
    protected String blockid;

    /**
     * Gets the value of the itemid property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getItemid() {
        return itemid;
    }

    /**
     * Sets the value of the itemid property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setItemid(String value) {
        this.itemid = value;
    }

    /**
     * Gets the value of the formposition property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFormposition() {
        return formposition;
    }

    /**
     * Sets the value of the formposition property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFormposition(String value) {
        this.formposition = value;
    }

    /**
     * Gets the value of the groupposition property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getGroupposition() {
        return groupposition;
    }

    /**
     * Sets the value of the groupposition property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setGroupposition(String value) {
        this.groupposition = value;
    }

    /**
     * Gets the value of the adminrequired property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAdminrequired() {
        if (adminrequired == null) {
            return "false";
        } else {
            return adminrequired;
        }
    }

    /**
     * Sets the value of the adminrequired property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAdminrequired(String value) {
        this.adminrequired = value;
    }

    /**
     * Gets the value of the responserequired property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getResponserequired() {
        if (responserequired == null) {
            return "false";
        } else {
            return responserequired;
        }
    }

    /**
     * Sets the value of the responserequired property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setResponserequired(String value) {
        this.responserequired = value;
    }

    /**
     * Gets the value of the isfieldtest property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIsfieldtest() {
        return isfieldtest;
    }

    /**
     * Sets the value of the isfieldtest property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIsfieldtest(String value) {
        this.isfieldtest = value;
    }

    /**
     * Gets the value of the isactive property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIsactive() {
        return isactive;
    }

    /**
     * Sets the value of the isactive property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIsactive(String value) {
        this.isactive = value;
    }

    /**
     * Gets the value of the blockid property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBlockid() {
        return blockid;
    }

    /**
     * Sets the value of the blockid property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBlockid(String value) {
        this.blockid = value;
    }

}
