//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.09.25 at 01:59:39 PM PDT 
//


package org.cresst.sb.irp.domain.testpackage;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the generated package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Passageref_QNAME = new QName("", "passageref");
    private final static QName _Description_QNAME = new QName("", "description");
    private final static QName _Comment_QNAME = new QName("", "comment");
    private final static QName _Bpref_QNAME = new QName("", "bpref");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: generated
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Itemscoredimension }
     * 
     */
    public Itemscoredimension createItemscoredimension() {
        return new Itemscoredimension();
    }

    /**
     * Create an instance of {@link Itemscoreparameter }
     * 
     */
    public Itemscoreparameter createItemscoreparameter() {
        return new Itemscoreparameter();
    }

    /**
     * Create an instance of {@link Property }
     * 
     */
    public Property createProperty() {
        return new Property();
    }

    /**
     * Create an instance of {@link Segmentbpelement }
     * 
     */
    public Segmentbpelement createSegmentbpelement() {
        return new Segmentbpelement();
    }

    /**
     * Create an instance of {@link Passage }
     * 
     */
    public Passage createPassage() {
        return new Passage();
    }

    /**
     * Create an instance of {@link Identifier }
     * 
     */
    public Identifier createIdentifier() {
        return new Identifier();
    }

    /**
     * Create an instance of {@link Administration }
     * 
     */
    public Administration createAdministration() {
        return new Administration();
    }

    /**
     * Create an instance of {@link Testblueprint }
     * 
     */
    public Testblueprint createTestblueprint() {
        return new Testblueprint();
    }

    /**
     * Create an instance of {@link Bpelement }
     * 
     */
    public Bpelement createBpelement() {
        return new Bpelement();
    }

    /**
     * Create an instance of {@link Poolproperty }
     * 
     */
    public Poolproperty createPoolproperty() {
        return new Poolproperty();
    }

    /**
     * Create an instance of {@link Itempool }
     * 
     */
    public Itempool createItempool() {
        return new Itempool();
    }

    /**
     * Create an instance of {@link Testitem }
     * 
     */
    public Testitem createTestitem() {
        return new Testitem();
    }

    /**
     * Create an instance of {@link Enemylist }
     * 
     */
    public Enemylist createEnemylist() {
        return new Enemylist();
    }

    /**
     * Create an instance of {@link Enemy }
     * 
     */
    public Enemy createEnemy() {
        return new Enemy();
    }

    /**
     * Create an instance of {@link Testform }
     * 
     */
    public Testform createTestform() {
        return new Testform();
    }

    /**
     * Create an instance of {@link Formpartition }
     * 
     */
    public Formpartition createFormpartition() {
        return new Formpartition();
    }

    /**
     * Create an instance of {@link Itemgroup }
     * 
     */
    public Itemgroup createItemgroup() {
        return new Itemgroup();
    }

    /**
     * Create an instance of {@link Groupitem }
     * 
     */
    public Groupitem createGroupitem() {
        return new Groupitem();
    }

    /**
     * Create an instance of {@link Adminsegment }
     * 
     */
    public Adminsegment createAdminsegment() {
        return new Adminsegment();
    }

    /**
     * Create an instance of {@link Segmentblueprint }
     * 
     */
    public Segmentblueprint createSegmentblueprint() {
        return new Segmentblueprint();
    }

    /**
     * Create an instance of {@link Itemselector }
     * 
     */
    public Itemselector createItemselector() {
        return new Itemselector();
    }

    /**
     * Create an instance of {@link Itemselectionparameter }
     * 
     */
    public Itemselectionparameter createItemselectionparameter() {
        return new Itemselectionparameter();
    }

    /**
     * Create an instance of {@link Segmentpool }
     * 
     */
    public Segmentpool createSegmentpool() {
        return new Segmentpool();
    }

    /**
     * Create an instance of {@link Segmentform }
     * 
     */
    public Segmentform createSegmentform() {
        return new Segmentform();
    }

    /**
     * Create an instance of {@link Computationruleparametervalue }
     * 
     */
    public Computationruleparametervalue createComputationruleparametervalue() {
        return new Computationruleparametervalue();
    }

    /**
     * Create an instance of {@link Testspecification }
     * 
     */
    public Testspecification createTestspecification() {
        return new Testspecification();
    }

    /**
     * Create an instance of {@link Registration }
     * 
     */
    public Registration createRegistration() {
        return new Registration();
    }

    /**
     * Create an instance of {@link Registrationform }
     * 
     */
    public Registrationform createRegistrationform() {
        return new Registrationform();
    }

    /**
     * Create an instance of {@link Registrationsegment }
     * 
     */
    public Registrationsegment createRegistrationsegment() {
        return new Registrationsegment();
    }

    /**
     * Create an instance of {@link Reporting }
     * 
     */
    public Reporting createReporting() {
        return new Reporting();
    }

    /**
     * Create an instance of {@link Performancelevels }
     * 
     */
    public Performancelevels createPerformancelevels() {
        return new Performancelevels();
    }

    /**
     * Create an instance of {@link Performancelevel }
     * 
     */
    public Performancelevel createPerformancelevel() {
        return new Performancelevel();
    }

    /**
     * Create an instance of {@link Reportingmeasures }
     * 
     */
    public Reportingmeasures createReportingmeasures() {
        return new Reportingmeasures();
    }

    /**
     * Create an instance of {@link Reportingmeasure }
     * 
     */
    public Reportingmeasure createReportingmeasure() {
        return new Reportingmeasure();
    }

    /**
     * Create an instance of {@link Scoretype }
     * 
     */
    public Scoretype createScoretype() {
        return new Scoretype();
    }

    /**
     * Create an instance of {@link Scoring }
     * 
     */
    public Scoring createScoring() {
        return new Scoring();
    }

    /**
     * Create an instance of {@link Scoringrules }
     * 
     */
    public Scoringrules createScoringrules() {
        return new Scoringrules();
    }

    /**
     * Create an instance of {@link Computationrule }
     * 
     */
    public Computationrule createComputationrule() {
        return new Computationrule();
    }

    /**
     * Create an instance of {@link Computationruleparameter }
     * 
     */
    public Computationruleparameter createComputationruleparameter() {
        return new Computationruleparameter();
    }

    /**
     * Create an instance of {@link Conversiontable }
     * 
     */
    public Conversiontable createConversiontable() {
        return new Conversiontable();
    }

    /**
     * Create an instance of {@link Conversiontuple }
     * 
     */
    public Conversiontuple createConversiontuple() {
        return new Conversiontuple();
    }

    /**
     * Create an instance of {@link Complete }
     * 
     */
    public Complete createComplete() {
        return new Complete();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "passageref")
    public JAXBElement<String> createPassageref(String value) {
        return new JAXBElement<String>(_Passageref_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "description")
    public JAXBElement<String> createDescription(String value) {
        return new JAXBElement<String>(_Description_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "comment")
    public JAXBElement<String> createComment(String value) {
        return new JAXBElement<String>(_Comment_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "bpref")
    public JAXBElement<String> createBpref(String value) {
        return new JAXBElement<String>(_Bpref_QNAME, String.class, null, value);
    }

}
