//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.09.25 at 01:59:39 PM PDT 
//


package org.cresst.sb.irp.domain.testpackage;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;attribute name="bpelementid" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="plevel" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="scaledlo" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="scaledhi" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "")
@XmlRootElement(name = "performancelevel")
public class Performancelevel {

    @XmlAttribute(name = "bpelementid", required = true)
    protected String bpelementid;
    @XmlAttribute(name = "plevel", required = true)
    protected String plevel;
    @XmlAttribute(name = "scaledlo", required = true)
    protected String scaledlo;
    @XmlAttribute(name = "scaledhi", required = true)
    protected String scaledhi;

    /**
     * Gets the value of the bpelementid property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBpelementid() {
        return bpelementid;
    }

    /**
     * Sets the value of the bpelementid property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBpelementid(String value) {
        this.bpelementid = value;
    }

    /**
     * Gets the value of the plevel property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPlevel() {
        return plevel;
    }

    /**
     * Sets the value of the plevel property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPlevel(String value) {
        this.plevel = value;
    }

    /**
     * Gets the value of the scaledlo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getScaledlo() {
        return scaledlo;
    }

    /**
     * Sets the value of the scaledlo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setScaledlo(String value) {
        this.scaledlo = value;
    }

    /**
     * Gets the value of the scaledhi property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getScaledhi() {
        return scaledhi;
    }

    /**
     * Sets the value of the scaledhi property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setScaledhi(String value) {
        this.scaledhi = value;
    }

}
