//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.09.25 at 01:59:39 PM PDT 
//


package org.cresst.sb.irp.domain.testpackage;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}testblueprint"/>
 *         &lt;element ref="{}performancelevels"/>
 *         &lt;element ref="{}reportingmeasures"/>
 *         &lt;element ref="{}itempool" minOccurs="0"/>
 *         &lt;element ref="{}testform" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "testblueprint",
    "performancelevels",
    "reportingmeasures",
    "itempool",
    "testform"
})
@XmlRootElement(name = "reporting")
public class Reporting {

    @XmlElement(required = true)
    protected Testblueprint testblueprint;
    @XmlElement(required = true)
    protected Performancelevels performancelevels;
    @XmlElement(required = true)
    protected Reportingmeasures reportingmeasures;
    protected Itempool itempool;
    protected List<Testform> testform;

    /**
     * Gets the value of the testblueprint property.
     * 
     * @return
     *     possible object is
     *     {@link Testblueprint }
     *     
     */
    public Testblueprint getTestblueprint() {
        return testblueprint;
    }

    /**
     * Sets the value of the testblueprint property.
     * 
     * @param value
     *     allowed object is
     *     {@link Testblueprint }
     *     
     */
    public void setTestblueprint(Testblueprint value) {
        this.testblueprint = value;
    }

    /**
     * Gets the value of the performancelevels property.
     * 
     * @return
     *     possible object is
     *     {@link Performancelevels }
     *     
     */
    public Performancelevels getPerformancelevels() {
        return performancelevels;
    }

    /**
     * Sets the value of the performancelevels property.
     * 
     * @param value
     *     allowed object is
     *     {@link Performancelevels }
     *     
     */
    public void setPerformancelevels(Performancelevels value) {
        this.performancelevels = value;
    }

    /**
     * Gets the value of the reportingmeasures property.
     * 
     * @return
     *     possible object is
     *     {@link Reportingmeasures }
     *     
     */
    public Reportingmeasures getReportingmeasures() {
        return reportingmeasures;
    }

    /**
     * Sets the value of the reportingmeasures property.
     * 
     * @param value
     *     allowed object is
     *     {@link Reportingmeasures }
     *     
     */
    public void setReportingmeasures(Reportingmeasures value) {
        this.reportingmeasures = value;
    }

    /**
     * Gets the value of the itempool property.
     * 
     * @return
     *     possible object is
     *     {@link Itempool }
     *     
     */
    public Itempool getItempool() {
        return itempool;
    }

    /**
     * Sets the value of the itempool property.
     * 
     * @param value
     *     allowed object is
     *     {@link Itempool }
     *     
     */
    public void setItempool(Itempool value) {
        this.itempool = value;
    }

    /**
     * Gets the value of the testform property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the testform property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getTestform().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Testform }
     * 
     * 
     */
    public List<Testform> getTestform() {
        if (testform == null) {
            testform = new ArrayList<Testform>();
        }
        return this.testform;
    }

}
