//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.09.02 at 01:50:33 PM PDT 
//


package org.cresst.sb.irp.domain.manifest;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the org.imsglobal.xsd.apip.apipv1p0.imscp_v1p1 package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: org.imsglobal.xsd.apip.apipv1p0.imscp_v1p1
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Manifest }
     * 
     */
    public Manifest createManifest() {
        return new Manifest();
    }

    /**
     * Create an instance of {@link Manifest.Resources }
     * 
     */
    public Manifest.Resources createManifestResources() {
        return new Manifest.Resources();
    }

    /**
     * Create an instance of {@link Manifest.Resources.Resource }
     * 
     */
    public Manifest.Resources.Resource createManifestResourcesResource() {
        return new Manifest.Resources.Resource();
    }

    /**
     * Create an instance of {@link NewDataSet }
     * 
     */
    public NewDataSet createNewDataSet() {
        return new NewDataSet();
    }

    /**
     * Create an instance of {@link Manifest.Metadata }
     * 
     */
    public Manifest.Metadata createManifestMetadata() {
        return new Manifest.Metadata();
    }

    /**
     * Create an instance of {@link Manifest.Resources.Resource.File }
     * 
     */
    public Manifest.Resources.Resource.File createManifestResourcesResourceFile() {
        return new Manifest.Resources.Resource.File();
    }

    /**
     * Create an instance of {@link Manifest.Resources.Resource.Dependency }
     * 
     */
    public Manifest.Resources.Resource.Dependency createManifestResourcesResourceDependency() {
        return new Manifest.Resources.Resource.Dependency();
    }

}
